### ISSUE TITLE
New Galxy version installed 24.1 or 23.1 ?

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#35]
Hi Christophe,

You update the deploy_galaxy.sh script yesterday, indicating that you move to 24.1 release of Galaxy. However, when I tested the installation this morning, it's version 23.1 that is installed.

Best
Stéphane

**Comment by drosofff** [comment]
This is because the update is done in the working branch #34 which is not merged yet with the main branch (the pull request is open and in wig status). You are likely testing the main branch.

**Comment by slecrom** [comment]
Is it possible to test the installation on the working branch or this not a good idea yet?

**Comment by drosofff** [comment]
Yes it is.
This is usually what you are doing.
But in this particular case, there is a small problem because the deploy script is called from another repo that point to the main branch of [AnalyseGenome](https://github.com/ARTbio/AnalyseGenome).

Thus, the only thing that you have to do is manually start le deployment on your VM using the command : 

```
wget https://raw.githubusercontent.com/ARTbio/AnalyseGenome/refs/heads/ag-2024/GalaxyServer/deploy_galaxy.sh && \
sh deploy_galaxy.sh
```

instead of : 

```
wget https://raw.githubusercontent.com/ARTbio/AnalyseGenome/main/GalaxyServer/deploy_galaxy.sh && \
sh deploy_galaxy.sh
```

It is working like a charm, by the way !

**Comment by slecrom** [comment]
I tested this new command and at It works!
